### PR TITLE
Fail tip selection when subtangle size is too big

### LINKED ISSUE #67: Throw exception in entryPointSelector if the subtangle size is too big
Suggested max size: `4 * MAX_FUTURE_SET_SIZE`.

Including entryPoint hash and its weight.

### PR DESCRIPTION
**Pull request by alongalky**
Fixes #67

### CODE REVIEW

File: src/main/java/com/iota/iri/service/tipselection/impl/EntryPointSelectorCumulativeWeightThreshold.java [hunk 1]
```diff
@@ -26,6 +26,8 @@
     private final Walker walker;
     private final WalkValidator walkValidator;
 
+    public static int MAX_SUBTANGLE_SIZE = CumulativeWeightCalculator.MAX_FUTURE_SET_SIZE;
```
Comment (alon-e) [inline src/main/java/com/iota/iri/service/tipselection/impl/EntryPointSelectorCumulativeWeightThreshold.java]:
```suggestion
    public static int MAX_SUBTANGLE_SIZE = CumulativeWeightCalculator.MAX_FUTURE_SET_SIZE * 4;
```

File: src/test/java/com/iota/iri/service/tipselection/impl/EntryPointSelectorCumulativeWeightThresholdTest.java [hunk 2]
```diff
@@ -146,4 +146,34 @@ public void callWalkerWhenSolidTipIsNull() throws Exception {
 
         Mockito.verify(walker, Mockito.times(1)).walk(Mockito.eq(Hash.NULL_HASH), Mockito.any(), Mockito.any());
     }
+
+    @Test
+    public void failWhenEntryPointSizeIsTooBig() throws Exception {
```
Comment (alon-e) [inline src/test/java/com/iota/iri/service/tipselection/impl/EntryPointSelectorCumulativeWeightThresholdTest.java:151]: add a test for between the ranges, this would have caught the `4 *` bug.

**Review by alon-e — CHANGES_REQUESTED** [review]

**Review by alon-e — APPROVED** [review]
