### PR TITLE
move tips population to `getLatestSolidTips`

### LINKED ISSUE #97: Bug: node gives error on startup
This is an issue caused by #96 .

Error log:

```
02/03 14:07:25.608 [Transaction Stats Publisher] ERROR c.i.i.s.s.TransactionStatsPublisher - Error while getting transaction counts : {}
java.lang.IllegalStateException: no tips found in largest connected component.
        at com.iota.iri.service.tipselection.impl.ConnectedComponentsStartingTipSelector.randomlySelectTipFromLargestConnectedComponent(ConnectedComponentsStartingTipSelector.java:120) ~[iri-oracle8.jar:na]
        at com.iota.iri.service.tipselection.impl.ConnectedComponentsStartingTipSelector.getTip(ConnectedComponentsStartingTipSelector.java:35) ~[iri-oracle8.jar:na]
        at com.iota.iri.service.tipselection.impl.EntryPointSelectorCumulativeWeightThreshold.getEntryPoint(EntryPointSelectorCumulativeWeightThreshold.java:39) ~[iri-oracle8.jar:na]
        at com.iota.iri.service.tipselection.impl.TipSelectorImpl.getTransactionsToApprove(TipSelectorImpl.java:72) ~[iri-oracle8.jar:na]
        at com.iota.iri.service.stats.TransactionStatsPublisher.getSuperTip(TransactionStatsPublisher.java:95) ~[iri-oracle8.jar:na]
        at com.iota.iri.service.stats.TransactionStatsPublisher.getConfirmedTransactionsCount(TransactionStatsPublisher.java:102) ~[iri-oracle8.jar:na]
        at com.iota.iri.service.stats.TransactionStatsPublisher.lambda$getRunnable$0(TransactionStatsPublisher.java:75) ~[iri-oracle8.jar:na]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
```

### PR DESCRIPTION
**Pull request by alon-e**
# Description

Tip population should be triggered by tip selection, and not a random tip request (which happens periodically) - b/c population might be a heavy process.

Fixes #97 

# How Has This Been Tested?
- Local node w/ empty DB, stopped producing that Exception.

### CODE REVIEW

**Comment by alon-e** [comment]
tests failed. reviewing.

**Comment by alon-e** [comment]
pushed fix

File: src/main/java/com/iota/iri/controllers/TipsViewModel.java [hunk 1]
```diff
@@ -1,18 +1,11 @@
...
-import java.util.LinkedList;
-import java.util.List;
-import java.util.Queue;
-import java.util.Set;
-
 import com.iota.iri.model.Hash;
 import com.iota.iri.storage.Tangle;
 
+import java.security.SecureRandom;
+import java.util.*;
```
Comment (alongalky) [inline src/main/java/com/iota/iri/controllers/TipsViewModel.java]: I prefer the specific import, but matter of taste I suppose

**Review by alongalky — APPROVED** [review]
