### PR TITLE
TipsViewModel populates solid tips when empty

### LINKED ISSUE #87: Populate tips when tipsViewModel is empty
When bootstrapping a CLIRI network new nodes cannot perform tip selection because `getEntryPoint` fails when `tipsViewModel.getRandomSolidTipHash()` returns `null`. To mitigate, we suggest identifying this flow and populating tips, by performing a graph traversal from the genesis.

### PR DESCRIPTION
**Pull request by alongalky**
Fixes #87 and #54

### CODE REVIEW

File: src/main/java/com/iota/iri/controllers/TipsViewModel.java [hunk 1]
```diff
@@ -57,13 +67,25 @@ public void setSolid(Hash tip) {
...
+        }
+
+        return result;
+    }
+
+    public Hash getRandomSolidTipHash() throws Exception {
         synchronized (sync) {
-            int size = solidTips.size();
-            if (size == 0) {
-                return null;
```
Comment (alon-e) [inline src/main/java/com/iota/iri/controllers/TipsViewModel.java:64]: what if no solid tip "exists" (after population the solidTips is empty)
it will still return `null`?

File: src/main/java/com/iota/iri/controllers/TipsViewModel.java [hunk 2]
```diff
@@ -118,7 +140,41 @@ public void clear() {
...
+  
+        // Create a queue for BFS
+        Queue<Hash> queue = new LinkedList<>(); 
+  
+        // Mark the genesis as visited and enqueue it 
+        visited.add(Hash.NULL_HASH);
+        queue.add(Hash.NULL_HASH); 
+  
+        Hash currentHash = Hash.NULL_HASH;
+        while (queue.size() != 0)
```
Comment (alon-e) [inline src/main/java/com/iota/iri/controllers/TipsViewModel.java]: `!queue.isEmpty()` reads better imo, shows intent.

File: src/test/java/com/iota/iri/controllers/TipsViewModelTest.java [hunk 3]
```diff
@@ -136,4 +157,67 @@ public void tipsEmtpyAfterClear() throws Exception {
...
+        solidTip.updateSolid(true);
+
+        solidTip.store(tangle);
+        nonSolidTip.store(tangle);
+
+        TipsViewModel tipsVM = new TipsViewModel(tangle);
+
+        Hash tip = tipsVM.getRandomSolidTipHash();
+
+        assertEquals(solidTip.getHash(), tip);
```
Comment (alon-e) [inline src/test/java/com/iota/iri/controllers/TipsViewModelTest.java:199]: would be better to explicitly show that `nonSolidTip` is not in the tips list.
this test could theoretically pass/fail wp 1/2 even if there is a bug and solid are not ignored.

File: src/test/java/com/iota/iri/controllers/TipsViewModelTest.java [hunk 4]
```diff
@@ -136,4 +157,67 @@ public void tipsEmtpyAfterClear() throws Exception {
...
+            
+            tipsVM.addTipHash(newTip.getHash());
+            tipsVM.setSolid(newTip.getHash());
+        }
+
+
+        List<Hash> tips = tipsVM.getLatestSolidTips(count);
+
+        assertNotNull(tips);
+        assertEquals(count, tips.size());
```
Comment (alon-e) [inline src/test/java/com/iota/iri/controllers/TipsViewModelTest.java:248]: maybe add a check for maintaining order? i.e. that these are the *last* 10 tips?

**Review by alon-e — CHANGES_REQUESTED** [review]

File: src/main/java/com/iota/iri/controllers/TipsViewModel.java (hunk 1 above)
Comment (alongalky) [reply src/main/java/com/iota/iri/controllers/TipsViewModel.java:64]: The correct behavior is to return only the genesis, I'll add a unit test to verify this happens

**Review by alon-e — APPROVED** [review]
